/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the first-run workspace state */
        get: operations["getOnboardingStatus"];
        put?: never;
        /** Initialize an empty workspace or explicitly install demo data */
        post: operations["initializeWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the persisted remediation workspace read model */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List managed companies */
        get: operations["listCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{companyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        /** Get one managed company */
        get: operations["getCompany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List persisted asset names referenced by findings */
        get: operations["listAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List normalized persisted findings */
        get: operations["listFindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{findingId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                findingId: components["parameters"]["FindingId"];
            };
            cookie?: never;
        };
        /** Get a finding with remediation, verification, evidence, and audit history */
        get: operations["getFinding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import one normalized finding into the local workspace */
        post: operations["createImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/remediations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a remediation record for an eligible finding */
        post: operations["createRemediation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/remediations/{remediationId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                remediationId: components["parameters"]["RemediationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete remediation and move the finding to awaiting verification */
        post: operations["completeRemediation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a principal-bound independent verification run
         * @description Verifier identity and credential class come from the server-established principal. The caller supplies source revision and patch digest provenance, but cannot override verifier identity. This endpoint does not execute commands or fetch arbitrary URLs.
         */
        post: operations["createVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verifications/{verificationId}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verificationId: components["parameters"]["VerificationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record one check result for a running verification */
        post: operations["createVerificationCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verifications/{verificationId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verificationId: components["parameters"]["VerificationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete a verification as Failed or atomically Verified fixed
         * @description A Passed completion records and locks evidence, completes the verification, transitions the finding to Verified fixed, and appends audit events in one transaction.
         */
        post: operations["completeVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List immutable evidence metadata */
        get: operations["listEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload and malware-scan an immutable evidence artifact */
        post: operations["uploadEvidenceArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{evidenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
            };
            cookie?: never;
        };
        /** Get immutable evidence metadata */
        get: operations["getEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{evidenceId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
            };
            cookie?: never;
        };
        /** Download an integrity-checked protected evidence artifact */
        get: operations["downloadEvidenceArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an immutable client report snapshot */
        post: operations["createReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        /** Get an immutable report snapshot */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{reportId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        /** Download a report snapshot as Markdown */
        get: operations["downloadReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List append-only audit events in sequence order */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List local webhook registrations
         * @description Local v1 does not deliver outbound webhooks and exposes no webhook mutation endpoint.
         */
        get: operations["listWebhooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List local integration capability states
         * @description Local v1 records no credentials and provides no managed connector execution.
         */
        get: operations["listIntegrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WorkspaceOrganization: {
            id: string;
            name: string;
            slug: string;
        };
        OnboardingStatus: {
            initialized: boolean;
            /** @enum {string|null} */
            mode: "empty" | "demo" | null;
            organization: components["schemas"]["WorkspaceOrganization"] | null;
        };
        InitializeWorkspaceRequest: {
            /** @constant */
            mode: "empty";
            organization_name: string;
            organization_slug: string;
        } | {
            /** @constant */
            mode: "demo";
        };
        /** @enum {string} */
        Severity: "Critical" | "High" | "Medium" | "Low" | "Info";
        /** @enum {string} */
        FindingState: "Needs remediation" | "Remediating" | "Awaiting verification" | "Verification failed" | "Verified fixed";
        /** @enum {string} */
        RemediationStatus: "In progress" | "Completed" | "Cancelled";
        /** @enum {string} */
        VerificationStatus: "Queued" | "Running" | "Passed" | "Failed" | "Cancelled";
        /** @enum {string} */
        VerificationCheckStatus: "Pending" | "Passed" | "Failed" | "Skipped";
        /** @enum {string} */
        RiskLevel: "Low" | "Medium" | "High" | "Critical";
        Company: {
            id: string;
            organization_id: string;
            name: string;
            risk_score: number;
            risk_level: components["schemas"]["RiskLevel"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AssetSummary: {
            company_id: string;
            name: string;
        };
        Finding: {
            id: string;
            organization_id: string;
            company_id: string;
            /** @example SEC-1042 */
            finding_key: string;
            title: string;
            description: string;
            source: string;
            severity: components["schemas"]["Severity"];
            state: components["schemas"]["FindingState"];
            owner: string;
            asset_name: string;
            /** Format: date-time */
            detected_at: string;
            /** Format: date-time */
            sla_due_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DashboardFinding: {
            id: string;
            organization_id: string;
            company_id: string;
            /** @example SEC-1042 */
            finding_key: string;
            title: string;
            description: string;
            source: string;
            severity: components["schemas"]["Severity"];
            state: components["schemas"]["FindingState"];
            owner: string;
            asset_name: string;
            /** Format: date-time */
            detected_at: string;
            /** Format: date-time */
            sla_due_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            company_name: string;
            sla_breached: boolean;
            priority_bucket: number;
        };
        FindingPage: {
            items: components["schemas"]["DashboardFinding"][];
            page: number;
            page_size: number;
            total: number;
        };
        Remediation: {
            id: string;
            finding_id: string;
            status: components["schemas"]["RemediationStatus"];
            summary: string;
            reference: string;
            owner: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            completed_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        VerificationRun: {
            id: string;
            finding_id: string;
            remediation_id: string;
            status: components["schemas"]["VerificationStatus"];
            method: string;
            worker_name: string;
            /** @enum {string} */
            credential_type: "session" | "local-process" | "legacy-assertion";
            execution_source: string;
            source_revision: string;
            patch_digest: string;
            scope: string;
            result_summary: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            completed_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        VerificationCheck: {
            id: string;
            verification_id: string;
            sequence: number;
            name: string;
            status: components["schemas"]["VerificationCheckStatus"];
            message: string;
            /** Format: date-time */
            created_at: string;
        };
        VerificationWithChecks: {
            verification: components["schemas"]["VerificationRun"];
            checks: components["schemas"]["VerificationCheck"][];
        };
        EvidenceItem: {
            id: string;
            finding_id: string;
            verification_id: string;
            kind: string;
            label: string;
            source_reference: string;
            content_hash: string;
            artifact_id: string | null;
            manifest_hash: string | null;
            manifest_signature: string | null;
            attested_by: string | null;
            metadata: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            locked_at: string | null;
        };
        AuditEvent: {
            id: number;
            organization_id: string;
            actor_type: string;
            actor_id: string;
            action: string;
            entity_type: string;
            entity_id: string;
            details: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            occurred_at: string;
        };
        AuditEventPage: {
            items: components["schemas"]["AuditEvent"][];
            page: number;
            page_size: number;
            total: number;
        };
        FindingDetail: {
            finding: components["schemas"]["Finding"];
            company: components["schemas"]["Company"];
            remediations: components["schemas"]["Remediation"][];
            verifications: components["schemas"]["VerificationWithChecks"][];
            evidence: components["schemas"]["EvidenceItem"][];
            audit_events: components["schemas"]["AuditEvent"][];
        };
        ImportRecord: {
            id: string;
            source: string;
            finding_id: string;
            /** Format: date-time */
            created_at: string;
        };
        ImportResult: {
            import_record: components["schemas"]["ImportRecord"];
            finding: components["schemas"]["Finding"];
        };
        DashboardMetrics: {
            managed_companies: number;
            open_findings: number;
            awaiting_verification: number;
            verification_failed: number;
            verified_fixed: number;
            sla_breaches: number;
        };
        CompanyRiskSummary: {
            company_id: string;
            company_name: string;
            risk_score: number;
            risk_level: components["schemas"]["RiskLevel"];
            open_findings: number;
            awaiting_verification: number;
            verification_failed: number;
        };
        VerificationActivity: {
            verification_id: string;
            finding_key: string;
            company_name: string;
            status: components["schemas"]["VerificationStatus"];
            result_summary: string;
            /** Format: date-time */
            completed_at: string | null;
        };
        NotificationItem: {
            id: string;
            /** @enum {string} */
            status: "attention" | "resolved";
            message: string;
        };
        DashboardSnapshot: {
            metrics: components["schemas"]["DashboardMetrics"];
            action_queue: components["schemas"]["DashboardFinding"][];
            companies: components["schemas"]["CompanyRiskSummary"][];
            verification_activity: components["schemas"]["VerificationActivity"][];
            notifications: components["schemas"]["NotificationItem"][];
            latest_report: components["schemas"]["Report"] | null;
        };
        ReportSnapshot: {
            company_name: string;
            risk_score: number;
            critical_findings: number;
            high_findings: number;
            verified_fixes: number;
            sla_compliance_percent: number;
            findings: components["schemas"]["Finding"][];
            verification_history: components["schemas"]["VerificationWithChecks"][];
        };
        Report: {
            id: string;
            company_id: string;
            title: string;
            period_label: string;
            /** @enum {string} */
            status: "Draft" | "Ready";
            snapshot: components["schemas"]["ReportSnapshot"];
            /** Format: date-time */
            generated_at: string;
            /** Format: date-time */
            created_at: string;
        };
        VerificationCompletion: {
            verification: components["schemas"]["VerificationRun"];
            finding: components["schemas"]["Finding"];
            evidence: components["schemas"]["EvidenceItem"][];
        };
        CreateImportRequest: {
            company_id: string;
            finding_key: string;
            title: string;
            description: string;
            source: string;
            severity: components["schemas"]["Severity"];
            owner: string;
            asset_name: string;
            /** Format: date-time */
            detected_at: string;
            /** Format: date-time */
            sla_due_at: string;
        };
        CreateRemediationRequest: {
            finding_id: string;
            owner: string;
            summary: string;
            reference: string;
        };
        CompleteRemediationRequest: {
            summary: string;
            reference: string;
        };
        CreateVerificationRequest: {
            finding_id: string;
            remediation_id: string;
            method: string;
            source_revision: string;
            patch_digest: string;
            scope: string;
            checks: string[];
        };
        CreateVerificationCheckRequest: {
            sequence: number;
            name: string;
            /** @enum {string} */
            status: "Passed" | "Failed" | "Skipped";
            message: string;
        };
        CreateEvidenceItem: {
            artifact_id: string;
            kind: string;
            label: string;
            source_reference: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        EvidenceArtifact: {
            id: string;
            content_hash: string;
            size_bytes: number;
            original_filename: string;
            /** @enum {string} */
            scan_status: "Clean";
            scanner: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            retention_until: string;
        };
        CompleteVerificationRequest: {
            /** @enum {string} */
            result: "Passed" | "Failed";
            summary: string;
            evidence?: components["schemas"]["CreateEvidenceItem"][];
        };
        CreateReportRequest: {
            company_id: string;
            period_label: string;
        };
        WebhookRegistration: {
            id: string;
            /** @enum {string} */
            status: "Disabled";
        };
        IntegrationState: {
            id: string;
            name: string;
            /** @enum {string} */
            status: "Not configured";
        };
        ProblemFieldError: {
            path: string;
            message: string;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail: string;
            /** Format: uri-reference */
            instance: string;
            code: string;
            request_id: string;
            errors?: components["schemas"]["ProblemFieldError"][];
        };
    };
    responses: {
        /** @description Request validation failed. */
        BadRequest: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The requested resource does not exist. */
        NotFound: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The requested mutation conflicts with persisted workflow state. */
        Conflict: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description JSON request body exceeds 256 KiB. */
        RequestTooLarge: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Uploaded content was rejected by the evidence security boundary. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A required protected dependency or artifact is unavailable. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unexpected server error without stack traces or local paths. */
        InternalError: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        CompanyId: string;
        FindingId: string;
        RemediationId: string;
        VerificationId: string;
        EvidenceId: string;
        ReportId: string;
        Search: string;
        CompanyQuery: string;
        StateQuery: components["schemas"]["FindingState"];
        SeverityQuery: components["schemas"]["Severity"];
        OwnerQuery: string;
        SortQuery: "priority" | "newest" | "sla";
        IncludeVerified: boolean;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation identifier for this request. */
        RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOnboardingStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current workspace initialization state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStatus"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    initializeWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitializeWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Workspace initialized exactly once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStatus"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getDashboard: {
        parameters: {
            query?: {
                search?: components["parameters"]["Search"];
                company_id?: components["parameters"]["CompanyQuery"];
                state?: components["parameters"]["StateQuery"];
                severity?: components["parameters"]["SeverityQuery"];
                owner?: components["parameters"]["OwnerQuery"];
                sort?: components["parameters"]["SortQuery"];
                include_verified?: components["parameters"]["IncludeVerified"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current dashboard metrics, queue, activity, notifications, and report state. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    listCompanies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Managed companies in the local organization. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                companyId: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Managed company. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listAssets: {
        parameters: {
            query?: {
                company_id?: components["parameters"]["CompanyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assets referenced by findings in the local organization. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetSummary"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listFindings: {
        parameters: {
            query?: {
                search?: components["parameters"]["Search"];
                company_id?: components["parameters"]["CompanyQuery"];
                state?: components["parameters"]["StateQuery"];
                severity?: components["parameters"]["SeverityQuery"];
                owner?: components["parameters"]["OwnerQuery"];
                sort?: components["parameters"]["SortQuery"];
                include_verified?: components["parameters"]["IncludeVerified"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated finding queue. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                findingId: components["parameters"]["FindingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Complete persisted finding detail. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateImportRequest"];
            };
        };
        responses: {
            /** @description Finding imported and audit history appended. */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["RequestTooLarge"];
            500: components["responses"]["InternalError"];
        };
    };
    createRemediation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRemediationRequest"];
            };
        };
        responses: {
            /** @description Remediation started. */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Remediation"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["RequestTooLarge"];
            500: components["responses"]["InternalError"];
        };
    };
    completeRemediation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                remediationId: components["parameters"]["RemediationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRemediationRequest"];
            };
        };
        responses: {
            /** @description Completed remediation. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Remediation"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["RequestTooLarge"];
            500: components["responses"]["InternalError"];
        };
    };
    createVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVerificationRequest"];
            };
        };
        responses: {
            /** @description Verification run created in Running state. */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationWithChecks"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["RequestTooLarge"];
            500: components["responses"]["InternalError"];
        };
    };
    createVerificationCheck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verificationId: components["parameters"]["VerificationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVerificationCheckRequest"];
            };
        };
        responses: {
            /** @description Verification check recorded. */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationCheck"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["RequestTooLarge"];
            500: components["responses"]["InternalError"];
        };
    };
    completeVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verificationId: components["parameters"]["VerificationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteVerificationRequest"];
            };
        };
        responses: {
            /** @description Verification completion and resulting finding state. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationCompletion"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["RequestTooLarge"];
            500: components["responses"]["InternalError"];
        };
    };
    listEvidence: {
        parameters: {
            query?: {
                finding_id?: string;
                verification_id?: string;
                locked?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evidence metadata matching the filters. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceItem"][];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    uploadEvidenceArtifact: {
        parameters: {
            query?: never;
            header: {
                "X-Evidence-Filename": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Artifact stored after a clean malware scan. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceArtifact"];
                };
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["RequestTooLarge"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evidence metadata. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceItem"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    downloadEvidenceArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Protected evidence bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportRequest"];
            };
        };
        responses: {
            /** @description Report snapshot created. */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["RequestTooLarge"];
            500: components["responses"]["InternalError"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Report metadata and snapshot. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    downloadReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Markdown rendering of the immutable report snapshot. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                entity_type?: string;
                entity_id?: string;
                from?: string;
                to?: string;
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered audit events. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local registrations. The v1 implementation returns an empty list. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookRegistration"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listIntegrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Integration capability states. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationState"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
